version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: zm-tg-notifier
    main: ./cmd/zm-tg-notifier
    binary: zm-tg-notifier
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

kos:
  - repository: ghcr.io/l13t/zm-tg-notifier
    tags:
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "{{ .Tag }}"
      - "{{if not .Prerelease}}stable{{end}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

release:
  github:
    owner: l13t
    name: zm-tg-notifier
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## ZoneMinder Telegram Event Bot

    {{ .Version }} Release
  footer: |
    **Full Changelog**: https://github.com/l13t/zm-tg-notifier/compare/{{ .PreviousTag }}...{{ .Tag }}